### ISSUE TITLE
@pictode/vue-aide安装错误

### ISSUE THREAD

**Issue by nickolboy** [JessYan0913/pictode#13]
### Bug Report / 缺陷报告

**问题描述 / Describe the bug**
[中文] 导入@pictode/vue-aide无法使用，找不到

**复现步骤 / To Reproduce**
[中文] 复现行为的步骤：
1. 使用pnpm安装@pictode/vue-aide
2. 在代码中import报错
3. 另外import的很多是type，git源代码中不是type，报错

**期望行为 / Expected behavior**
[English] A clear and concise description of what you expected to happen.
[中文] 请清晰简明地描述您期望发生的行为。

**截图 / Screenshots**
[中文] vue-aide的package信息错误
![image](https://github.com/JessYan0913/pictode/assets/2337029/2c6f51aa-239d-4d83-86c5-7183887494e0)

**Comment by JessYan0913** [comment]
已经修正

**Comment by JessYan0913** [comment]
https://github.com/JessYan0913/pictode/pull/20
