### ISSUE TITLE
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  pictode@0.0.1-beta01 dev: `vite`

### ISSUE THREAD

**Issue by wjyzhixing** [JessYan0913/pictode#16]
<img width="570" alt="image" src="https://github.com/JessYan0913/pictode/assets/36620969/fd2248a6-3b63-434b-b2f0-6980c72efd39">

<img width="243" alt="image" src="https://github.com/JessYan0913/pictode/assets/36620969/a6a789bd-843e-4bef-b4d0-285b68a3b14f">

**Comment by wjyzhixing** [comment]
when I run "npm run pictode" some error occured

**Comment by JessYan0913** [comment]
> when I run "npm run pictode" some error occured

1. Install pnpm first

```shell
npm install -g pnpm
```

2. Install dependencies

```shell
pnpm bootstrap
```

3. Start the project

```shell
pnpm pictode
```
