### ISSUE TITLE
文本工具输入时看不到光标

### ISSUE THREAD

**Issue by nickolboy** [JessYan0913/pictode#17]
### Bug Report / 缺陷报告

**问题描述 / Describe the bug**
[中文] 文本编辑时看不到光标

[中文] 复现行为的步骤：
1. 打开一个弹窗进行绘画
2. 点击文本工具
3. 双击画板空白处，无任何效果。
4. 输入后，点击其他空白区域，显示出文字

**期望行为 / Expected behavior**
[中文] pictode创建输入框使用了一个absolute的textarea，但是没有设置zIndex，当在弹窗中打开pcitode时，弹窗的div挡住了textarea。希望配置增加个zindex，并有默认值

**Comment by knightgao** [comment]
Could you provide an example for this? I couldn't reproduce it successfully.

**Comment by nickolboy** [comment]
> Could you provide an example for this? I couldn't reproduce it successfully.

位置貌似也不对

<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);border-radius:2px;" width="800" height="450" src="https://codesandbox.io/p/sandbox/pictode-playground-forked-sdhzrq?file=%2Fsrc%2FApp.vue%3A1%2C1&embed=1" allowfullscreen></iframe>

**Comment by JessYan0913** [comment]
> > Could you provide an example for this? I couldn't reproduce it successfully.你能举个例子吗？我无法成功复制它。
> 
> 位置貌似也不对，这样看textarea应该放在pictode的容器内比较好，也不用设置了
> 
> https://codesandbox.io/p/sandbox/pictode-playground-forked-sdhzrq?file=%2Fsrc%2FApp.vue%3A1%2C1

嗯嗯我刚才检查了一下，确实是因为<textarea>的位置计算错了。

![image](https://github.com/JessYan0913/pictode/assets/52144974/0eb3bf69-2b48-4028-b81b-1f06a73b7574)

我们会尽快处理这个BUG

**Comment by nickolboy** [comment]
> > > Could you provide an example for this? I couldn't reproduce it successfully.你能举个例子吗？我无法成功复制它。
> > 
> > 
> > 位置貌似也不对，这样看textarea应该放在pictode的容器内比较好，也不用设置了
> > https://codesandbox.io/p/sandbox/pictode-playground-forked-sdhzrq?file=%2Fsrc%2FApp.vue%3A1%2C1
> 
> 嗯嗯我刚才检查了一下，确实是因为<textarea>的位置计算错了。
> 
> ![image](https://user-images.githubusercontent.com/52144974/277527765-0eb3bf69-2b48-4028-b81b-1f06a73b7574.png)
> 
> 我们会尽快处理这个BUG

该这样呢？
```
const handleTextDoubleClick = (app: App, textNode: Konva.Text, onUpdated: () => void) => {
  ...
  let textarea = document.createElement('textarea');
  app.stage.container().appendChild(textarea);
  textarea.value = textNode.text();
  ...
```

**Comment by JessYan0913** [comment]
> > > > Could you provide an example for this? I couldn't reproduce it successfully.你能举个例子吗？我无法成功复制它。你能举个例子吗？我无法成功复制它。你能举个例子吗？我无法成功复制它。
> > > 
> > > 
> > > 位置貌似也不对，这样看textarea应该放在pictode的容器内比较好，也不用设置了
> > > https://codesandbox.io/p/sandbox/pictode-playground-forked-sdhzrq?file=%2Fsrc%2FApp.vue%3A1%2C1
> > 
> > 
> > 嗯嗯我刚才检查了一下，确实是因为<textarea>的位置计算错了。
> > ![image](https://user-images.githubusercontent.com/52144974/277527765-0eb3bf69-2b48-4028-b81b-1f06a73b7574.png)
> > 我们会尽快处理这个BUG
> 
> 该这样呢？
> 
> ```
> const handleTextDoubleClick = (app: App, textNode: Konva.Text, onUpdated: () => void) => {
>   ...
>   let textarea = document.createElement('textarea');
>   app.stage.container().appendChild(textarea);
>   textarea.value = textNode.text();
>   ...
> ```

安装新版的tools包试试，`@pictode/tools@0.0.1-beta04`

**Comment by JessYan0913** [comment]
> > > > Could you provide an example for this? I couldn't reproduce it successfully.你能举个例子吗？我无法成功复制它。你能举个例子吗？我无法成功复制它。你能举个例子吗？我无法成功复制它。
> > > 
> > > 
> > > 位置貌似也不对，这样看textarea应该放在pictode的容器内比较好，也不用设置了
> > > https://codesandbox.io/p/sandbox/pictode-playground-forked-sdhzrq?file=%2Fsrc%2FApp.vue%3A1%2C1
> > 
> > 
> > 嗯嗯我刚才检查了一下，确实是因为<textarea>的位置计算错了。
> > ![image](https://user-images.githubusercontent.com/52144974/277527765-0eb3bf69-2b48-4028-b81b-1f06a73b7574.png)
> > 我们会尽快处理这个BUG
> 
> 该这样呢？
> 
> ```
> const handleTextDoubleClick = (app: App, textNode: Konva.Text, onUpdated: () => void) => {
>   ...
>   let textarea = document.createElement('textarea');
>   app.stage.container().appendChild(textarea);
>   textarea.value = textNode.text();
>   ...
> ```

你这个方案应会更好一些，随后再更新一下吧，textTool组件代码有点乱
