### ISSUE TITLE
支持文本换行,即多行文本

### ISSUE THREAD

**Issue by moshuiyan** [JessYan0913/pictode#46]
### Feature Request / 功能请求

**特性描述 /  Feature Description**
目前输入文本只能单行， 无法换行。不知是否实现
**解决方案描述 / Solution Description**
换行效果，参考https://excalidraw.com/
**技术实现建议 / Technical Implementation Suggestions**
如果还是输入框实现的文本输入， 那么文本测量确实是个问题。 我目前采用的是用浏览器测量法。 比较简单粗暴。 [demo](https://code.juejin.cn/pen/7248601050658111548)

**Comment by JessYan0913** [comment]
`@pictode/tools`中的文本工具支持多行输入，目前设计的是`shift + ctrl`来进行换行

**Comment by JessYan0913** [comment]
> `@pictode/tools`中的文本工具支持多行输入，目前设计的是`shift + ctrl`来进行换行

不过目前文本工具确实存在很多问题，这次一并修复吧

**Comment by JessYan0913** [comment]
目前文本工具的问题：

- 无法回车换行（目前需要`shift+enter`）
- 选中时编辑文本选择框无动态跟随
- 编辑中textarea区域尺寸计算不正确

![文本工具问题](https://github.com/JessYan0913/pictode/assets/52144974/b71962f3-575d-4975-ae4a-01d435736409)

![image](https://github.com/JessYan0913/pictode/assets/52144974/4fe6b5ce-7505-4af1-825c-debb9f4d86e1)
