### ISSUE TITLE
node在初次编辑缩放旋转时回退存在异常

### ISSUE THREAD

**Issue by Symbol-ZJJ** [JessYan0913/pictode#55]
### Bug Report / 缺陷报告

**问题描述 / Describe the bug**

node在初次编辑缩放旋转时回退存在异常

**复现步骤 / To Reproduce**

1. 创建node
2. 编辑node
3. 撤销
4. nod没有恢复到编辑前的node

**期望行为 / Expected behavior**

nod正常恢复到编辑前的node

**Comment by JessYan0913** [comment]
> ### Bug Report / 缺陷报告
> **问题描述 / Describe the bug**
> 
> node在初次编辑缩放旋转时回退存在异常
> 
> **复现步骤 / To Reproduce**
> 
> 1. 创建node
> 2. 编辑node
> 3. 撤销
> 4. nod没有恢复到编辑前的node
> 
> **期望行为 / Expected behavior**
> 
> nod正常恢复到编辑前的node

找到问题在哪了`polyfill/index.ts`中的`import './node';`未在顶部引用，导致圆形和线条的第一次形变时无法获取到默认的`scale`等值。这是`Konva`作者为了减少`toObject`输入内容，所以当一个属性值是默认值时，`toObject`就会将其省略。

![image](https://github.com/JessYan0913/pictode/assets/52144974/84cf281f-ff77-4082-aab0-b62be3acfd94)
