### ISSUE TITLE
[Feature]鼠标中键进行画布拖拽的功能有点局限

### ISSUE THREAD

**Issue by Symbol-ZJJ** [JessYan0913/pictode#66]
### Feature Request / 功能请求

**特性描述 /  Feature Description**

实际使用中的并不需要鼠标中键进行拖拽的功能

**解决方案描述 / Solution Description**

希望拖拽功能可以按需灵活使用或者禁止掉

**Comment by JessYan0913** [comment]
可以考虑将是否绑定中键移动画布交给使用者来决定
