### ISSUE TITLE
[BUG] 添加本地图片后保存到本地，重新导入该文件渲染时报错

### ISSUE THREAD

**Issue by web-dahuyou** [JessYan0913/pictode#68]
### Bug Report / 缺陷报告

**问题描述 / Describe the bug**
画板中包含本地图片时，导出文件后，再次导入失败，报错

**复现步骤 / To Reproduce**
1、在空白画板中选择添加本地图片，然后点击 `菜单 -> 保存到本地`， 假设自动下载的文件名为 `xxx.pictode`
2、点击 `菜单 -> 打开` 重新加载刚才保存的 `xxx.pictode` 文件
3、你会发现报错了

**期望行为 / Expected behavior**
能正常导出、导入，可以在导出时过滤掉本地图片

**截图 / Screenshots**
<img width="592" alt="image" src="https://github.com/JessYan0913/pictode/assets/22833786/deef96d6-261f-43a2-af73-7b66776b9160">

**Comment by JessYan0913** [comment]
BUG验证通过
